import io
import random
from datetime import timedelta

from django.core.files.base import ContentFile
from django.core.management.base import BaseCommand
from django.utils import timezone

from event.models import Event
from shop.models import EventGallery


try:
    from PIL import Image, ImageDraw, ImageFont
except Exception:  # pragma: no cover - Pillow should be installed
    Image = None


class Command(BaseCommand):
    help = "Seed EventGallery with generated placeholder photos for testing the album/lightbox UI"

    def add_arguments(self, parser):
        parser.add_argument(
            "--per-event",
            type=int,
            default=6,
            help="Number of photos to create per event (default: 6)",
        )
        parser.add_argument(
            "--max-events",
            type=int,
            default=8,
            help="Maximum number of events to seed (default: 8)",
        )
        parser.add_argument(
            "--public-only",
            action="store_true",
            default=True,
            help="Create photos as public (default: True)",
        )
        parser.add_argument(
            "--width",
            type=int,
            default=1600,
            help="Placeholder image width (default: 1600)",
        )
        parser.add_argument(
            "--height",
            type=int,
            default=900,
            help="Placeholder image height (default: 900)",
        )

    def handle(self, *args, **options):
        if Image is None:
            self.stderr.write(self.style.ERROR("Pillow is required to run this command (pip install Pillow)"))
            return

        per_event = options["per_event"]
        max_events = options["max_events"]
        is_public = options["public_only"]
        width = options["width"]
        height = options["height"]

        events = list(
            Event.objects.order_by("-event_date")[: max_events]
        )

        if not events:
            self.stderr.write(self.style.WARNING("No events found. Create events first."))
            return

        total_created = 0
        now = timezone.now()

        for event in events:
            self.stdout.write(f"Seeding photos for event: {event.name}")
            # Stagger upload times for ordering
            base_time = now - timedelta(days=random.randint(0, 30))

            for idx in range(per_event):
                title = f"{event.name} - Photo {idx + 1}"

                # Generate placeholder image
                image_bytes = self._generate_placeholder_image(
                    width=width,
                    height=height,
                    bg_color=self._random_brand_color(),
                    text=title,
                )

                photo_file = ContentFile(image_bytes.getvalue())
                photo_filename = f"gallery/events/{event.slug.replace(' ', '_')}_{idx + 1}.jpg"

                gallery = EventGallery(
                    event=event,
                    title=title,
                    description=f"Autogenerated placeholder for {event.name}",
                    is_public=is_public,
                    is_featured=(idx == 0),
                    uploaded_by=None,
                )
                # First save to get an ID and file path
                gallery.photo.save(photo_filename, photo_file, save=False)
                gallery.save()

                # Adjust uploaded_at to base_time + idx to create a timeline
                gallery.uploaded_at = base_time + timedelta(minutes=idx)
                gallery.save(update_fields=["uploaded_at"])
                total_created += 1

            self.stdout.write(self.style.SUCCESS(f"  ✓ Created {per_event} photos"))

        self.stdout.write(self.style.SUCCESS(f"Done. Created {total_created} gallery photos across {len(events)} events."))
        self.stdout.write("You can now visit the gallery home to test the album/lightbox UI.")

    def _generate_placeholder_image(self, width: int, height: int, bg_color: tuple, text: str) -> io.BytesIO:
        img = Image.new("RGB", (width, height), color=bg_color)
        draw = ImageDraw.Draw(img)

        # Try to load a decent font; fallback to default
        try:
            font = ImageFont.truetype("arial.ttf", size=int(height * 0.06))
        except Exception:
            font = ImageFont.load_default()

        # Text box
        text_lines = [text, "Eventlinez Placeholder"]
        line_spacing = 10
        line_heights = []
        line_widths = []
        for line in text_lines:
            # Pillow 10+ removed textsize; use textbbox
            bbox = draw.textbbox((0, 0), line, font=font)
            w = bbox[2] - bbox[0]
            h = bbox[3] - bbox[1]
            line_widths.append(w)
            line_heights.append(h)

        total_text_height = sum(line_heights) + line_spacing * (len(text_lines) - 1)
        max_text_width = max(line_widths)

        x = (width - max_text_width) // 2
        y = (height - total_text_height) // 2

        # Draw shadow for readability
        for offset in [(2, 2), (1, 1)]:
            yy = y
            for i, line in enumerate(text_lines):
                w = line_widths[i]
                draw.text((x + offset[0], yy + offset[1]), line, font=font, fill=(0, 0, 0))
                yy += line_heights[i] + line_spacing

        # Draw text
        yy = y
        for i, line in enumerate(text_lines):
            w = line_widths[i]
            draw.text((x, yy), line, font=font, fill=(255, 255, 255))
            yy += line_heights[i] + line_spacing

        out = io.BytesIO()
        img.save(out, format="JPEG", quality=85)
        out.seek(0)
        return out

    def _random_brand_color(self) -> tuple:
        # Some vibrant colors that fit the site's palette
        palette = [
            (217, 0, 117),    # pink
            (255, 107, 157),  # light pink
            (82, 91, 212),    # indigo
            (46, 196, 182),   # teal
            (255, 159, 67),   # orange
            (76, 201, 240),   # sky
        ]
        return random.choice(palette)


