# Generated by Django 3.1.2 on 2020-11-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cellphone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
