# Generated by Django 3.1.5 on 2021-04-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20210404_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='NC', max_length=250),
            preserve_default=False,
        ),
    ]
