# Generated by Django 3.1.5 on 2021-05-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20210410_0639'),
        ('customer', '0008_customer_city'),
    ]

    operations = [
    ]
