# Generated by Django 3.2.4 on 2021-06-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20210410_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='terms_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
