# Generated by Django 3.1.5 on 2021-05-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_merge_20210503_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='zip',
            field=models.CharField(default='00000', max_length=11),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(default='NC', max_length=250),
        ),
    ]
