# Generated by Django 3.1.3 on 2021-06-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20210504_1137'),
        ('customer', '0009_customer_terms_confirmed'),
    ]

    operations = [
    ]
