# Generated by Django 3.1.5 on 2021-06-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20210504_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='terms_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
