# Generated by Django 3.2.4 on 2021-06-12 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_customer_terms_confirmed'),
        ('customer', '0012_customer_terms_confirmed'),
    ]

    operations = [
    ]
