# Generated by Django 3.1.3 on 2021-06-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_merge_20210613_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='terms_confirmed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
