# Generated by Django 3.2.25 on 2026-06-27 01:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket', '0013_remove_is_cancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketShareToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked', models.BooleanField(default=False)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_tokens', to='ticket.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
