# Generated by Django 3.1.2 on 2020-11-09 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='price',
            new_name='unit_price',
        ),
    ]
