# Generated by Django 3.1.2 on 2020-11-16 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20201111_2144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventItem',
        ),
    ]
