# Generated by Django 3.1.2 on 2020-11-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_delete_eventitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoter',
            name='email',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
