# Generated by Django 3.1.2 on 2020-11-25 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0006_promoter_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoter',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promoter', to=settings.AUTH_USER_MODEL),
        ),
    ]
