# Generated by Django 3.1.2 on 2020-11-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20201125_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoter',
            name='address_promoter',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
