# Generated by Django 3.1.2 on 2020-11-25 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_auto_20201111_2144'),
        ('event', '0009_auto_20201125_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoter',
            name='address_promoter',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.PROTECT, to='address.address'),
        ),
    ]
