# Generated by Django 3.1.2 on 2020-11-25 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20201125_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promoter',
            old_name='address_promoter',
            new_name='address',
        ),
    ]
