# Generated by Django 3.1.2 on 2020-11-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20201125_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoter',
            name='city',
            field=models.CharField(default='Fortaleza', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promoter',
            name='zip',
            field=models.CharField(default='6298000', max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promoter',
            name='address',
            field=models.CharField(default='Rua delta', max_length=250),
            preserve_default=False,
        ),
    ]
