# Generated by Django 3.1.2 on 2020-11-27 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0012_auto_20201125_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='promoter', to='auth.user'),
        ),
    ]
