# Generated by Django 3.1.2 on 2020-11-27 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20201127_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='promoter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='event.promoter'),
            preserve_default=False,
        ),
    ]
