# Generated by Django 3.1.2 on 2020-11-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_auto_20201127_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoter',
            name='email',
            field=models.CharField(default='no@body.com', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
