# Generated by Django 3.1.2 on 2020-12-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_auto_20201129_1929'),
        ('event', '0015_auto_20201204_1533'),
    ]

    operations = [
    ]
