# Generated by Django 3.1.2 on 2020-12-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_address',
        ),
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default='NC', max_length=300),
            preserve_default=False,
        ),
    ]
