# Generated by Django 3.1.2 on 2020-12-17 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_auto_20201111_2144'),
        ('event', '0018_auto_20201216_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='address.city'),
        ),
    ]
