# Generated by Django 3.1.2 on 2021-01-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_ticket_price'),
    ]

    operations = [
    ]
