# Generated by Django 3.1.5 on 2021-01-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_auto_20210106_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoter',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='promoter',
            name='social_security',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
