# Generated by Django 3.1.5 on 2021-01-22 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_auto_20210122_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promoter',
            old_name='social_security',
            new_name='ssn',
        ),
    ]
