# Generated by Django 3.1.2 on 2021-04-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_auto_20210122_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='guest_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
