# Generated by Django 3.1.2 on 2021-04-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_auto_20210410_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='guest_name',
            field=models.CharField(blank=True, max_length=161, null=True),
        ),
    ]
