# Generated by Django 3.2.4 on 2021-06-13 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0026_auto_20210429_0627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
