# Generated by Django 3.1.3 on 2021-06-13 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0028_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='stock',
        ),
    ]
