# Generated by Django 3.1.3 on 2021-06-16 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0029_remove_event_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='unit_price',
        ),
    ]
