# Generated by Django 3.1.3 on 2021-06-28 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0030_remove_event_unit_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Event'},
        ),
    ]
