# Generated by Django 3.1.3 on 2021-07-20 02:28

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0031_auto_20210627_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(help_text='The recommended dimensions is 1600 x 838. Images with different dimensions will be resized. The image can not be greater than 3MB', upload_to='event', validators=[event.models.validate_image]),
        ),
    ]
