# Generated by Django 3.1.3 on 2021-11-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0001_initial'),
        ('event', '0032_auto_20210719_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='vendors',
            field=models.ManyToManyField(blank=True, to='promoter.Vendor'),
        ),
    ]
