# Generated by Django 3.1.3 on 2021-11-10 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0032_auto_20210719_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(default='', max_length=250)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('promoter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.promoter')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='vendors',
            field=models.ManyToManyField(to='event.Vendor'),
        ),
    ]
