# Generated by Django 3.1.3 on 2021-11-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0033_auto_20211110_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='vendors',
            field=models.ManyToManyField(blank=True, to='event.Vendor'),
        ),
    ]
