# Generated by Django 3.1.3 on 2022-01-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0033_event_vendors'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoter',
            name='id_conect',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
