# Generated by Django 3.1.3 on 2022-01-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0034_promoter_id_conect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promoter',
            old_name='id_conect',
            new_name='account_id',
        ),
    ]
