# Generated by Django 3.1.3 on 2024-02-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0036_auto_20230323_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
