# Generated by Django 3.2.25 on 2025-10-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0038_auto_20250829_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_free_event',
            field=models.BooleanField(default=False, help_text='Mark this event as free'),
        ),
    ]
