# Generated by Django 3.2.25 on 2026-05-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0039_event_is_free_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='days',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of days this ticket covers. E.g. 3 for a Full Pass (3-day ticket).'),
        ),
    ]
