# Generated by Django 3.2.25 on 2026-05-02 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0040_ticket_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullPassEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField(help_text='Which day this event corresponds to (1, 2, 3...)')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_pass_ticket_days', to='event.event')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_pass_events', to='event.ticket')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('ticket', 'day_number')},
            },
        ),
    ]
