# Generated by Django 3.1.3 on 2021-06-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0030_remove_event_unit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ManyToManyField(to='event.Event')),
            ],
        ),
    ]
