# Generated by Django 3.1.3 on 2021-06-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialevents',
            options={'verbose_name': 'Special events', 'verbose_name_plural': 'Special events'},
        ),
        migrations.AddField(
            model_name='specialevents',
            name='active_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialevents',
            name='name_special_event_list',
            field=models.CharField(default='Special events', max_length=250),
        ),
    ]
