# Generated by Django 3.1.3 on 2021-09-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('link', models.CharField(max_length=250)),
            ],
        ),
    ]
