# Generated by Django 3.1.3 on 2021-11-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='vendor',
            name='last_name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
