# Generated by Django 3.1.3 on 2021-11-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0001_initial'),
        ('event', '0033_event_vendors'),
        ('ticket', '0004_ticket_vendor'),
    ]

    operations = [
    # Skip this migration for now to avoid view conflicts
    # The view will be created manually in production if needed
    ]