# Generated by Django 3.1.3 on 2022-09-18 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0035_auto_20220119_0435'),
        ('promoter', '0002_sales_by_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='payments')),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.promoter')),
            ],
            options={
                'verbose_name': 'Payments',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last4', models.CharField(max_length=4)),
                ('bank_name', models.CharField(max_length=250)),
                ('routing_number', models.CharField(max_length=64)),
                ('promoter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event.promoter')),
            ],
        ),
    ]
