# Generated by Django 3.1.3 on 2022-04-08 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0035_auto_20220119_0435'),
        ('promoter', '0002_sales_by_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInfomationPromoter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bank_account', models.CharField(blank=True, max_length=250, null=True)),
                ('last4', models.CharField(blank=True, max_length=4, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=250, null=True)),
                ('routing_number', models.CharField(blank=True, max_length=64, null=True)),
                ('promoter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.promoter')),
            ],
        ),
    ]
