# Generated by Django 3.1.3 on 2022-09-28 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0003_bankaccount_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='last4',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(default=1234567890, max_length=12, validators=[django.core.validators.RegexValidator('^[0-9+]', 'Only digit characters.')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='description',
            field=models.CharField(default='Send Payment', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='routing_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[0-9+]', 'Only digit characters.')]),
        ),
    ]
