# Generated by Django 3.1.3 on 2022-04-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0035_auto_20220119_0435'),
        ('promoter', '0003_bankinfomationpromoter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankInfomationPromoter',
            new_name='BankAccount',
        ),
    ]
