# Generated by Django 3.1.3 on 2022-04-14 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0035_auto_20220119_0435'),
        ('promoter', '0004_auto_20220413_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='promoter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.promoter'),
        ),
    ]
