# Generated by Django 3.1.3 on 2022-09-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0004_auto_20220928_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='description',
        ),
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
