# Generated by Django 3.1.3 on 2022-09-11 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0035_auto_20220119_0435'),
        ('promoter', '0005_auto_20220414_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='payments')),
                ('promoter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.promoter')),
            ],
            options={
                'verbose_name': 'Payments',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
