# Generated by Django 3.1.3 on 2022-11-29 22:27

import django.core.validators
from django.db import migrations, models
import promoter.models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0005_auto_20220929_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[0-9+]', 'Only digit numeric.'), promoter.models.min_validation_none]),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+', 'Only letters')]),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='routing_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[0-9+]', 'Only digit numeric.'), promoter.models.min_validation_none]),
        ),
    ]
