# Generated by Django 3.1.3 on 2024-02-06 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0036_auto_20230323_1822'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promoter', '0006_auto_20221129_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_at', models.DateTimeField(auto_created=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('DOORMAN', 'Doorman'), ('BUSINESS_PARTNER', 'Businness Partner')], max_length=40)),
                ('disable', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
