# Generated by Django 3.1.3 on 2022-09-17 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0035_auto_20220119_0435'),
        ('promoter', '0006_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='payments'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='promoter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.promoter'),
        ),
    ]
