# Generated by Django 3.1.3 on 2025-04-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0007_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='role',
            field=models.CharField(choices=[('DOORMAN', 'Doorman'), ('PARTNER', 'Businnes Partner')], max_length=40),
        ),
    ]
