# Generated by Django 3.1.2 on 2020-11-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zipcode',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
