# Generated by Django 3.1.2 on 2020-11-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20201110_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True),
        ),
    ]
