# Generated by Django 3.1.2 on 2020-11-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='promo_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
