# Generated by Django 3.1.2 on 2020-11-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_promo_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='promo_code',
        ),
        migrations.AddField(
            model_name='cart',
            name='promo_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
