# Generated by Django 3.1.2 on 2020-11-14 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20201114_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='promo_code',
        ),
    ]
