# Generated by Django 3.1.2 on 2020-11-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='promo_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
