# Generated by Django 3.1.2 on 2020-11-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cartitem_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='promoter',
            field=models.CharField(default='promoters', max_length=255),
        ),
    ]
