# Generated by Django 3.1.2 on 2020-11-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cartitem_promoter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='promoter',
            field=models.CharField(max_length=255),
        ),
    ]
