# Generated by Django 3.1.2 on 2020-11-27 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20201127_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='promoter',
        ),
    ]
