# Generated by Django 3.1.3 on 2021-06-16 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0029_remove_event_stock'),
        ('cart', '0008_remove_cartitem_promoter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='event',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.ticket'),
            preserve_default=False,
        ),
    ]
