# Generated by Django 3.1.3 on 2021-11-18 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0001_initial'),
        ('cart', '0009_auto_20210616_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='promoter.vendor'),
        ),
    ]
