# Generated by Django 3.2.25 on 2025-09-15 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0011_auto_20250829_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbandonedCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('items_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abandoned_at', models.DateTimeField()),
                ('reminder_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Reminder Sent'), ('converted', 'Converted to Order'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.PositiveIntegerField(default=0)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abandoned_cart', to='cart.cart')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abandoned Cart',
                'verbose_name_plural': 'Abandoned Carts',
                'ordering': ['-abandoned_at'],
            },
        ),
        migrations.CreateModel(
            name='AbandonedCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_name', models.CharField(max_length=255)),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateTimeField()),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('abandoned_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.abandonedcart')),
            ],
            options={
                'verbose_name': 'Abandoned Cart Item',
                'verbose_name_plural': 'Abandoned Cart Items',
            },
        ),
    ]
