# Generated by Django 3.2.25 on 2025-10-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_abandonedcart_abandonedcartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='applied_promo_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='promo_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
