# Generated by Django 3.2.25 on 2025-10-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_auto_20251013_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='session_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
