# Generated by Django 3.2.25 on 2025-10-14 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_auto_20251014_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='session_expires_at',
        ),
    ]
