# Generated by Django 3.1.3 on 2021-06-13 14:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0012_merge_20210613_0523'),
        ('order', '0012_orderitem_fee'),
        ('event', '0028_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('guest_name', models.CharField(blank=True, max_length=161, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
                ('event_ticket', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='event.ticket')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.orderitem')),
            ],
        ),
    ]
