# Generated by Django 3.1.3 on 2021-08-03 13:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='checkin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
