# Generated by Django 3.1.3 on 2021-11-10 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0033_auto_20211110_1128'),
        ('ticket', '0003_auto_20210803_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.vendor'),
        ),
    ]
