# Generated by Django 3.1.3 on 2024-03-06 16:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0037_ticket_sold_out'),
        ('ticket', '0004_ticket_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='guest_name',
            field=models.CharField(default='NONAME', max_length=161),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FreeTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=161)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('checkin_date', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('account_required', models.BooleanField()),
                ('is_email_sent', models.BooleanField(default=False)),
                ('event_ticket', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='event.ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
