# Generated by Django 3.1.3 on 2024-02-19 20:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0036_auto_20230323_1822'),
        ('ticket', '0004_ticket_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('guest_name', models.CharField(max_length=161)),
                ('required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('checkin_date', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='event.event')),
            ],
        ),
    ]
