# Generated by Django 3.1.3 on 2025-04-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_ticket_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
