# Generated by Django 3.1.3 on 2024-02-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_freeticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeticket',
            name='is_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
