# Generated by Django 3.1.3 on 2025-04-08 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_ticket_sold_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='sold_out',
        ),
    ]
