# Generated by Django 3.1.3 on 2024-02-20 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_freeticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freeticket',
            old_name='required',
            new_name='account_required',
        ),
    ]
