# Generated by Django 3.2.25 on 2025-10-21 00:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0039_event_is_free_event'),
        ('ticket', '0007_alter_ticket_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplimentaryTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=20)),
                ('ticket_type', models.CharField(choices=[('GUEST_LIST', 'Guest List'), ('VIP', 'VIP'), ('PRESS', 'Press'), ('COMP', 'Complimentary'), ('STAFF', 'Staff')], default='GUEST_LIST', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('CHECKED_IN', 'Checked In'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('checkin_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this guest')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complimentary_tickets', to='event.event')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_complimentary_tickets', to='event.promoter')),
            ],
            options={
                'verbose_name': 'Complimentary Ticket',
                'verbose_name_plural': 'Complimentary Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='complimentaryticket',
            index=models.Index(fields=['event', 'status'], name='ticket_comp_event_i_3be532_idx'),
        ),
        migrations.AddIndex(
            model_name='complimentaryticket',
            index=models.Index(fields=['uuid'], name='ticket_comp_uuid_a5f8b1_idx'),
        ),
        migrations.AddIndex(
            model_name='complimentaryticket',
            index=models.Index(fields=['guest_email'], name='ticket_comp_guest_e_94939d_idx'),
        ),
    ]
