# Generated by Django 3.2.25 on 2026-05-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20251020_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='day_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='For multi-day passes: which day this ticket is valid for (1, 2, 3...).', null=True),
        ),
    ]
