# Generated by Django 3.2.25 on 2026-05-02 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0041_fullpassevent'),
        ('ticket', '0009_ticket_day_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='day_event',
            field=models.ForeignKey(blank=True, help_text='For multi-day passes: the specific event this day ticket is valid for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_tickets', to='event.event'),
        ),
    ]
