# Generated by Django 3.2.25 on 2026-05-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_ticket_day_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
