# Generated by Django 3.2.25 on 2026-05-31 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0042_description_rich_text_uploading'),
        ('customer', '0014_alter_customer_id'),
        ('promoter', '0010_promocode_promocodeusage'),
        ('order', '0016_refund_model'),
        ('ticket', '0011_add_is_cancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_ticket_id', models.IntegerField()),
                ('uuid', models.UUIDField(db_index=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guest_name', models.CharField(blank=True, max_length=161, null=True)),
                ('day_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('original_checkin_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.CharField(choices=[('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='REFUNDED', max_length=20)),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_tickets', to='customer.customer')),
                ('day_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_day_tickets', to='event.event')),
                ('event_ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_tickets', to='event.ticket')),
                ('order_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_tickets', to='order.orderitem')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promoter.vendor')),
            ],
        ),
    ]
