# Generated by Django 3.2.25 on 2026-05-31 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_add_cancelled_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_cancelled',
        ),
    ]
