# Generated by Django 3.1.2 on 2020-11-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20201110_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_code',
            field=models.CharField(default='-1', max_length=200),
            preserve_default=False,
        ),
    ]
