# Generated by Django 3.1.2 on 2020-11-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_payment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='promo_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
