# Generated by Django 3.1.2 on 2020-11-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_promoter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='promoter',
            field=models.CharField(max_length=255),
        ),
    ]
