# Generated by Django 3.1.2 on 2020-11-27 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20201127_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promoter',
        ),
    ]
