# Generated by Django 3.1.2 on 2020-11-27 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20201127_0524'),
        ('order', '0007_remove_order_promoter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
    ]
