# Generated by Django 3.1.2 on 2020-12-20 23:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20201220_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
