# Generated by Django 3.1.3 on 2021-06-13 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0028_ticket'),
        ('order', '0012_orderitem_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='event',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='event_ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.ticket'),
            preserve_default=False,
        ),
    ]
