# Generated by Django 3.1.3 on 2024-06-27 21:57

from django.db import migrations, models


def set_default_creation_method(apps, schema_editor):
    order = apps.get_model('order', 'order')
    order.objects.all().update(creation_method='CHECKOUT_SESSION')


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_orderitem_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='creation_method',
            field=models.CharField(
                choices=[('CHECKOUT_SESSION', 'Checkout Session'), ('WEBHOOK', 'Webhook')],
                max_length=20,
                null=True,  # Permitir nulos temporariamente
            ),
        ),
        migrations.RunPython(set_default_creation_method),
        migrations.AlterField(
            model_name='order',
            name='creation_method',
            field=models.CharField(
                choices=[('CHECKOUT_SESSION', 'Checkout Session'), ('WEBHOOK', 'Webhook')],
                max_length=20,
                null=False,  # Não permitir nulos após a atualização das linhas existentes
            ),
        ),
    ]
