# Generated by Django 4.2.25 on 2026-05-31 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0015_auto_20250829_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='PAID', max_length=20),
        ),
        migrations.CreateModel(
            name='TicketRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_refund_id', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField(blank=True)),
                ('refunded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='order.order')),
                ('refunded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_refunds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
