# Generated by Django 4.2.25 on 2026-06-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_refund_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='promo_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
