# Generated by Django 3.2.25 on 2026-07-02 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_extend_promo_code_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_to', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('bounced', models.BooleanField(default=False)),
                ('bounce_reason', models.TextField(blank=True)),
                ('resent_at', models.DateTimeField(blank=True, null=True)),
                ('sendgrid_message_id', models.CharField(blank=True, max_length=200)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_log', to='order.order')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
